apiVersion: v1
kind: Pod
metadata:
  name: demo-entrypoint
  labels:
    app: demo-entrypoint
spec:
  containers:
    - name: saludo
      image: edgaregonzalez/entrypoint-test:v0.0.1
      args: ["--saludo", "Hola desde kubernetes!"]
      imagePullPolicy: Always