version: '3.8'
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"